name = "withered-mud-dc44"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
ALLOWED_ORIGIN = "https://dualpost.app"
REDIRECT_URI = "https://dualpost.app/yt-callback.html"

[[kv_namespaces]]
binding = "PUSH_KV"
id = "f590c96fa0a045f09586230d6656ea6d"
